"""
=============================================================
agents/wardrobe_architect_agent.py — Style Agent Gold Standard
=============================================================
PURPOSE:
  This is Agent 4 — the Wardrobe Architect.
  Its job is to build 3 complete outfit options, one per
  colour palette generated by Agent 3.

  For each outfit, it queries the current_inventory SQLite table
  and picks an item for EVERY required outfit slot:
    1. Top (or Dress — picks a full-body option if available)
    2. Bottom (or skips if a dress was chosen)
    3. Outerwear (blazer / jacket / dupatta / shrug / cape)
    4. Footwear
    5. Bag

  Every item description is written at premium stylist quality:
  NOT "Blue kurta, white palazzo"
  YES "Powder blue silk-georgette A-line kurta with gold border"

  It also writes a WHY_THIS_WORKS explanation and OCCASION_NOTES
  for each outfit.
=============================================================
"""

import sqlite3    # built-in library for database queries
import os         # built-in library for file paths
import random     # built-in library for picking variety

# ── Path to the database file ─────────────────────────────────
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(PROJECT_ROOT, "database", "inventory.db")


# =============================================================
# CLASS: WardrobeArchitectAgent
# =============================================================
class WardrobeArchitectAgent:
    """
    Agent 4: Queries the inventory and builds 3 complete outfits,
    each based on one of the 3 colour palettes from Agent 3.
    """

    def __init__(self):
        """Set up the agent."""
        pass  # no setup needed — we open the DB connection per query

    # ─────────────────────────────────────────────────────────
    # HELPER: _get_db_connection
    # Opens a database connection with dict-style row access
    # ─────────────────────────────────────────────────────────
    def _get_db_connection(self):
        """Opens inventory.db and enables dict-style column access."""
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row  # allows row["column_name"]
        return conn

    # ─────────────────────────────────────────────────────────
    # HELPER: _find_item
    # Queries inventory for ONE item matching the given conditions
    # ─────────────────────────────────────────────────────────
    def _find_item(self, cursor, category, vibe, occasion, budget_max, size,
                   preferred_colour=None, exclude_ids=None):
        """
        Searches current_inventory for an item matching all filters.

        category:         e.g. 'Top', 'Bottom', 'Dress', 'Footwear', 'Bag'
        vibe:             e.g. 'Ethnic', 'Modern', 'Boho'
        occasion:         e.g. 'wedding', 'office', 'date_night'
        budget_max:       maximum price the user will pay
        size:             the user's clothing size
        preferred_colour: if given, try to match this colour first
        exclude_ids:      list of item_ids already chosen (to avoid repeats)

        Returns: a dict of item data, or None if nothing found
        """
        if exclude_ids is None:
            exclude_ids = []  # default to empty list

        # Build the SQL WHERE clause for excluded IDs
        # If no IDs to exclude, use "1=1" which matches everything
        if exclude_ids:
            exclude_placeholder = ",".join("?" * len(exclude_ids))
            exclude_clause = f"AND item_id NOT IN ({exclude_placeholder})"
        else:
            exclude_clause = ""

        # We try with colour preference first, then without
        for try_colour in ([preferred_colour, None] if preferred_colour else [None]):
            # Build colour filter SQL
            if try_colour:
                colour_clause = "AND lower(colour) LIKE ?"
                colour_param  = [f"%{try_colour.lower()}%"]
            else:
                colour_clause = ""
                colour_param  = []

            # Build the complete SQL query
            # We use LIKE for occasion matching because occasions are comma-separated
            query = f"""
                SELECT * FROM current_inventory
                WHERE category = ?
                  AND lower(vibe) = ?
                  AND lower(occasion_tags) LIKE ?
                  AND price <= ?
                  AND lower(size_available) LIKE ?
                  {colour_clause}
                  {exclude_clause}
                ORDER BY RANDOM()
                LIMIT 1
            """

            # Combine all query parameters into one list
            params = (
                [category, vibe.lower(), f"%{occasion.lower()}%",
                 budget_max, f"%{size.lower()}%"]
                + colour_param
                + exclude_ids  # the excluded IDs go last
            )

            cursor.execute(query, params)
            row = cursor.fetchone()  # get the first matching row

            if row:
                return dict(row)  # found something! Convert to dict and return

        # Nothing found with the strict vibe filter — try with any vibe
        fallback_query = f"""
            SELECT * FROM current_inventory
            WHERE category = ?
              AND lower(occasion_tags) LIKE ?
              AND price <= ?
              AND lower(size_available) LIKE ?
              {exclude_clause}
            ORDER BY RANDOM()
            LIMIT 1
        """
        fallback_params = (
            [category, f"%{occasion.lower()}%", budget_max, f"%{size.lower()}%"]
            + exclude_ids
        )
        cursor.execute(fallback_query, fallback_params)
        row = cursor.fetchone()
        return dict(row) if row else None

    # ─────────────────────────────────────────────────────────
    # HELPER: _describe_item
    # Formats one inventory item into a premium-quality description
    # ─────────────────────────────────────────────────────────
    def _describe_item(self, item_dict):
        """
        Converts a raw database row into a rich, stylist-quality description.
        Example: "Powder blue silk-georgette A-line kurta with gold zari border"
        """
        if not item_dict:
            return "No matching item found for this slot"

        # The item name from the database is already detailed
        # We enrich it with additional styling context
        name    = item_dict.get("item_name", "Fashion item")    # full descriptive name
        colour  = item_dict.get("colour", "")
        fabric  = item_dict.get("fabric", "")
        sil     = item_dict.get("silhouette", "")               # e.g. A-Line, Wide Leg
        cut     = item_dict.get("cut", "")                      # e.g. Anarkali, Wrap
        fit     = item_dict.get("fit", "")                      # e.g. Regular, Slim
        price   = item_dict.get("price", 0)
        brand   = item_dict.get("brand_tier", "Mid-range")

        return {
            "name":        name,          # the full item description
            "colour":      colour,
            "fabric":      fabric,
            "silhouette":  sil,
            "cut":         cut,
            "fit":         fit,
            "price":       f"₹{price:,.0f}",  # format with rupee sign and commas
            "brand_tier":  brand,
            "item_id":     item_dict.get("item_id", 0),
        }

    # ─────────────────────────────────────────────────────────
    # METHOD: _write_why_this_works
    # Writes a 3-sentence stylist explanation for each outfit
    # ─────────────────────────────────────────────────────────
    def _write_why_this_works(self, top, bottom_or_dress, outerwear, palette, occasion, vibe):
        """
        Creates a human-sounding, 3-sentence explanation of why
        this colour combination and outfit works for this occasion.
        """
        # Get the primary piece — either top or dress
        main_piece = top if top else bottom_or_dress
        main_colour = main_piece.get("colour", "this hue") if main_piece else "this hue"

        explanation = (
            f"The {palette.get('harmony_type', 'colour')} palette anchors the look in {palette.get('primary_colour', main_colour)}, "
            f"with {palette.get('secondary_colour', 'complementary tones')} as the natural counterpart — "
            f"a pairing that creates visual interest without sacrificing elegance. "
            f"For a {occasion.replace('_', ' ').title()} occasion, the {vibe} aesthetic balances cultural context "
            f"with individual expression — you will feel like yourself, only at your most elevated. "
            f"The fabric and silhouette choices ensure comfort across the duration of the event "
            f"without ever compromising on visual impact."
        )
        return explanation

    # ─────────────────────────────────────────────────────────
    # METHOD: _write_occasion_notes
    # Two specific styling tips for the chosen occasion
    # ─────────────────────────────────────────────────────────
    def _write_occasion_notes(self, occasion, vibe):
        """
        Returns 2 actionable, occasion-specific styling tips.
        """
        # Map occasions to specific, useful tips
        notes_library = {
            "wedding": [
                "Pin your dupatta to your shoulder for maximum movement during dance sequences.",
                "Carry a small potli bag — a large tote reads too casual at a wedding. Keep essentials minimal.",
            ],
            "sangeet": [
                "Opt for footwear with a block heel or kitten heel — you will be dancing for hours.",
                "Layer your jewellery from lightweight to statement — start minimal and add as the evening progresses.",
            ],
            "office": [
                "Tuck your blouse in precisely — a clean tuck signals intentionality and confidence.",
                "Keep accessories monochromatic with your outfit palette so attention stays on your work, not the style clash.",
            ],
            "date_night": [
                "Let one element be the statement — either the outfit OR the jewellery, never both at full volume.",
                "Spritz fragrance at the wrist pulse points and the back of the neck — never on fabric as it can stain.",
            ],
            "festival": [
                "Choose breathable fabrics — cotton, chanderi, or georgette — for outdoor festival settings.",
                "Secure all jewellery properly before exploring crowded fair grounds.",
            ],
            "mehendi": [
                "Avoid fitted sleeves — you will need easy access for your hands during the mehendi application.",
                "Choose colours in the green-yellow family to complement the henna tones beautifully in photographs.",
            ],
        }

        # Return tips for the specific occasion, or generic tips if not in library
        return notes_library.get(occasion.lower(), [
            f"Dress one level above what you think is required for a {occasion.replace('_', ' ').title()} — you will never regret being slightly overdressed.",
            "Carry a few safety pins, some body tape, and a small perfume — a prepared outfit is a confident outfit.",
        ])

    # ─────────────────────────────────────────────────────────
    # METHOD: _build_one_outfit
    # Builds a single complete outfit from inventory
    # ─────────────────────────────────────────────────────────
    def _build_one_outfit(self, cursor, palette, persona, occasion, vibe, budget_max, size, outfit_number):
        """
        Queries inventory to fill all 5 outfit slots for one palette.
        Returns a complete outfit dictionary.
        """
        chosen_ids   = []    # track chosen item IDs to avoid duplicates
        primary_col  = palette.get("primary_colour", "")
        secondary_col = palette.get("secondary_colour", "")

        # ── Slot 1: Try Dress first, then Top ───────────────────
        # If we find a full Dress, we skip searching for a Bottom
        dress = self._find_item(cursor, "Dress", vibe, occasion, budget_max, size, primary_col, chosen_ids)
        if dress:
            chosen_ids.append(dress["item_id"])  # mark as taken
            top  = None
            bottom = None
        else:
            # No dress found — look for a separate Top
            top = self._find_item(cursor, "Top", vibe, occasion, budget_max, size, primary_col, chosen_ids)
            if top:
                chosen_ids.append(top["item_id"])

            # Then look for a matching Bottom in the secondary colour
            bottom = self._find_item(cursor, "Bottom", vibe, occasion, budget_max, size, secondary_col, chosen_ids)
            if bottom:
                chosen_ids.append(bottom["item_id"])

        # ── Slot 2: Outerwear ────────────────────────────────────
        outerwear = self._find_item(cursor, "Outerwear", vibe, occasion, budget_max, size, None, chosen_ids)
        if outerwear:
            chosen_ids.append(outerwear["item_id"])

        # ── Slot 3: Footwear ─────────────────────────────────────
        # Footwear uses "All Sizes" so we query differently
        footwear = self._find_item(cursor, "Footwear", vibe, occasion, budget_max, "All Sizes", None, chosen_ids)
        if footwear:
            chosen_ids.append(footwear["item_id"])

        # ── Slot 4: Bag ──────────────────────────────────────────
        bag = self._find_item(cursor, "Bag", vibe, occasion, budget_max, "One Size", None, chosen_ids)
        if bag:
            chosen_ids.append(bag["item_id"])

        # ── Calculate total outfit cost ──────────────────────────
        total_cost = sum([
            (dress    or {}).get("price", 0),
            (top      or {}).get("price", 0),
            (bottom   or {}).get("price", 0),
            (outerwear or {}).get("price", 0),
            (footwear or {}).get("price", 0),
            (bag      or {}).get("price", 0),
        ])

        # ── Write stylist notes ──────────────────────────────────
        why_this_works  = self._write_why_this_works(top or dress, bottom, outerwear, palette, occasion, vibe)
        occasion_notes  = self._write_occasion_notes(occasion, vibe)

        # ── Assemble the outfit dict ─────────────────────────────
        outfit = {
            "outfit_number":   outfit_number,
            "palette_name":    f"Option {['A','B','C'][outfit_number - 1]} — {palette.get('harmony_type', 'Curated')} Palette",
            "colour_swatches": [
                {"name": palette.get("primary_colour",   "Primary"),   "hex": palette.get("primary_hex",   "#000")},
                {"name": palette.get("secondary_colour", "Secondary"), "hex": palette.get("secondary_hex", "#888")},
                {"name": palette.get("accent_colour",    "Accent"),    "hex": palette.get("accent_hex",    "#FFF")},
            ],
            "items": {
                "dress":     self._describe_item(dress)     if dress     else None,
                "top":       self._describe_item(top)       if top       else None,
                "bottom":    self._describe_item(bottom)    if bottom    else None,
                "outerwear": self._describe_item(outerwear) if outerwear else None,
                "footwear":  self._describe_item(footwear)  if footwear  else None,
                "bag":       self._describe_item(bag)        if bag       else None,
            },
            "total_estimated_cost": f"₹{total_cost:,.0f}",
            "why_this_works":       why_this_works,
            "occasion_notes":       occasion_notes,
            "colour_rationale":     palette.get("colour_rationale", ""),
        }

        return outfit

    # ─────────────────────────────────────────────────────────
    # METHOD: run — THE MAIN ENTRY POINT
    # ─────────────────────────────────────────────────────────
    def run(self, palettes, persona, occasion, vibe):
        """
        Builds 3 complete outfits — one per colour palette.

        palettes: list of 3 palette dicts from ColourEngineAgent
        persona:  dict from PersonaAgent with budget, size, etc.
        occasion: e.g. 'wedding', 'office', 'date_night'
        vibe:     e.g. 'Ethnic', 'Modern', 'Boho'

        Returns: list of 3 outfit dicts
        """
        print(f"  👗 Wardrobe Architect: Building 3 looks for {occasion} ({vibe} vibe)...")

        # Get user constraints from persona
        budget_max = persona.get("budget_max", 15000)
        size       = persona.get("size", "M")

        conn   = self._get_db_connection()
        cursor = conn.cursor()

        outfits = []  # list to collect all 3 completed outfits

        # Loop through each palette and build one outfit per palette
        for outfit_number, palette in enumerate(palettes, start=1):
            outfit = self._build_one_outfit(
                cursor, palette, persona, occasion, vibe, budget_max, size, outfit_number
            )
            outfits.append(outfit)
            print(f"  ✅  Outfit {outfit_number} ({palette.get('harmony_type', '')}) assembled")

        conn.close()  # close the database connection
        print(f"  ✅ All 3 outfits ready!")
        return outfits  # return the list of 3 outfit dicts
